### PR TITLE
Specialize folds for Chain, FlatMap, and Inspect

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Comment by sfackler** [comment]
Let's bump the minimum supported Rust version to 1.27 and specialize try_fold instead to get better coverage.

**Comment by sfackler** [comment]
Scratch that, try_fold uses the unstable Try trait.

**Comment by cuviper** [comment]
Thanks. These are `StreamingIterator` anyway, which doesn't have `try_fold` yet.

FWIW, we added that in rayon `ParallelIterator` with our own pub-in-private `Try`, implemented only for `Option` and `Result`. This way we have the freedom to update to stable `Try` later.

**Comment by sfackler** [comment]
Hmm, try_fold might not really make sense for StreamingIterator anyway until it's GAT-ified. The situations where you can return an `&Option<T>` or `&Result<T, E>` seem pretty obscure compared to mapping into a normal iterator and using that.

**Pull request merged**
