### PR TITLE
Add map_deref and filter_map_deref

### PR DESCRIPTION
**Pull request by Palladinium**
Grants #9's wish in a backwards-compatible manner

### CODE REVIEW

**Comment by sfackler** [comment]
LGTM but needs a rebase

**Comment by cuviper** [comment]
Thanks!

Looks like this got the rebase already.

**Comment by cuviper** [comment]
It would be nice to specialize `Iterator::fold` for these too.
(`DoubleEndedIterator::rfold` requires 1.27.)

**Comment by Palladinium** [comment]
I'm not sure I follow, Rust stable is at 1.35, what's the issue with 1.27?

**Comment by cuviper** [comment]
Many crates choose to support more than just the latest stable, and some even consider it a breaking change to raise the required rustc. I don't know @sfackler's position on that, but we don't need to have that argument here. Just note that streaming-iterator's CI is currently running 1.19.

**Comment by Palladinium** [comment]
Ah, I didn't realize that. I'll add `fold` for now and wait for @sfackler's decision.

**Comment by sfackler** [comment]
I think it's probably fine to bump to 1.27 - that's been around for a while now. Alternatively we could use a build script to detect the rustc version and conditionally compile.

**Comment by sfackler** [comment]
You'd actually want to override try_fold, since that's what the default implementation of fold itself uses: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.try_fold

**Comment by sfackler** [comment]
Sorry for not seeing the rebase, btw - Github doesn't send emails when PRs are force-pushed :(

**Comment by cuviper** [comment]
You can't write `Iterator::try_fold` until `Try` is stable.

**Comment by sfackler** [comment]
Oh right, nevermind then!

**Pull request merged**
